#!/bin/bash
# ============================================
# LifeOS cPanel Installation Script
# ============================================
# Usage: bash install.sh
#
# Prerequisites:
#   - cPanel hosting with Node.js Selector (Node.js >= 18)
#   - MySQL database created via cPanel > MySQL Databases
#   - Database user created and assigned to the database
#   - SSH access or cPanel Terminal
# ============================================

set -e

echo ""
echo "╔══════════════════════════════════════╗"
echo "║     LifeOS cPanel Installer          ║"
echo "╚══════════════════════════════════════╝"
echo ""

# Detect app directory
APP_DIR=$(pwd)
echo "📁 Installing in: $APP_DIR"
echo ""

# --- Gather Database Info ---
read -p "🗄️  cPanel Username Prefix (e.g. arif_): " DB_PREFIX
read -p "🗄️  Database Name (without prefix, e.g. lifeos): " DB_NAME_RAW
read -p "👤 Database Username (without prefix, e.g. lifeos): " DB_USER_RAW
read -sp "🔑 Database Password: " DB_PASSWORD
echo ""

FULL_DB_NAME="${DB_PREFIX}${DB_NAME_RAW}"
FULL_DB_USER="${DB_PREFIX}${DB_USER_RAW}"

echo ""
echo "📋 Database: $FULL_DB_NAME"
echo "📋 Username: $FULL_DB_USER"
echo ""

# --- Generate JWT Secret ---
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 64)

# --- Create .env file ---
cat > "$APP_DIR/.env" << EOF
# LifeOS Self-Hosted Configuration (cPanel)
# Generated by install.sh on $(date)

DB_TYPE=mysql
DB_HOST=localhost
DB_PORT=3306
DB_NAME=$FULL_DB_NAME
DB_USER=$FULL_DB_USER
DB_PASSWORD=$DB_PASSWORD

JWT_SECRET=$JWT_SECRET
API_PORT=3001
NODE_ENV=production

VITE_SELFHOSTED_API_URL=/api
VITE_SUPABASE_URL=
VITE_SUPABASE_PUBLISHABLE_KEY=
EOF

echo "✅ .env file created"

# --- Install dependencies ---
echo "📦 Installing Node.js dependencies..."
if command -v npm &> /dev/null; then
  npm install --production 2>/dev/null || npm install
  echo "✅ Dependencies installed"
else
  echo "⚠️  npm not found. Please install Node.js 18+ via cPanel > Node.js Selector"
  exit 1
fi

# --- Build frontend ---
echo "🔨 Building frontend..."
npm run build 2>/dev/null && echo "✅ Frontend built" || echo "⚠️  Build skipped (may need dev dependencies: npm install)"

# --- Create .htaccess for API proxy ---
cat > "$APP_DIR/.htaccess" << 'EOF'
# LifeOS - Apache Rewrite Rules for cPanel
# Proxy API requests to Node.js backend

RewriteEngine On

# Proxy /api requests to Node.js backend
RewriteRule ^api/(.*)$ http://127.0.0.1:3001/api/$1 [P,L]

# Serve static files from dist/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ dist/index.html [L]

# Security headers
Header set X-Content-Type-Options "nosniff"
Header set X-Frame-Options "SAMEORIGIN"
Header set X-XSS-Protection "1; mode=block"
Header set Referrer-Policy "strict-origin-when-cross-origin"

# Cache static assets
<FilesMatch "\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$">
  Header set Cache-Control "max-age=31536000, public"
</FilesMatch>

# Disable directory listing
Options -Indexes
EOF

echo "✅ .htaccess created"

# --- Create PM2/forever startup script ---
cat > "$APP_DIR/start-backend.sh" << 'EOF'
#!/bin/bash
# Start LifeOS Backend
# Run this via cPanel Cron Job or Node.js Selector

cd "$(dirname "$0")"
export $(cat .env | grep -v '^#' | xargs)
node docker/backend/server.js
EOF
chmod +x "$APP_DIR/start-backend.sh"

echo "✅ start-backend.sh created"

# --- Test database connection ---
echo ""
echo "🔗 Testing database connection..."
node -e "
const mysql = require('mysql2/promise');
(async () => {
  try {
    const conn = await mysql.createConnection({
      host: 'localhost',
      port: 3306,
      database: '$FULL_DB_NAME',
      user: '$FULL_DB_USER',
      password: '$DB_PASSWORD',
    });
    await conn.query('SELECT 1');
    await conn.end();
    console.log('✅ Database connection successful!');
  } catch (err) {
    console.log('⚠️  Could not connect to database:', err.message);
    console.log('   Make sure the database and user are created in cPanel > MySQL Databases');
  }
})();
" 2>/dev/null || echo "⚠️  mysql2 not installed yet. Connection will be tested during setup wizard."

echo ""
echo "╔══════════════════════════════════════╗"
echo "║     Installation Complete! 🎉        ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "📋 Next Steps:"
echo "   1. Start the backend:  bash start-backend.sh"
echo "   2. Or add to cPanel Cron:  @reboot cd $APP_DIR && bash start-backend.sh"
echo "   3. Visit your domain to complete setup"
echo ""
echo "📋 cPanel Node.js Selector:"
echo "   - Application root: $(basename $APP_DIR)"
echo "   - Application startup file: docker/backend/server.js"
echo "   - Node.js version: 18+"
echo ""
echo "🔒 Your JWT secret has been generated automatically."
echo "📁 Config file: $APP_DIR/.env"
echo ""
